### ISSUE TITLE
how to compile on windows?

### ISSUE THREAD

**Issue by gitthismoney** [lloeki/matterfront#17]
can someone provide me info on how to compile an exe of this? I did get the os x version working, thanks.

**Comment by LongLiveCHIEF** [comment]
I'm working on a PR that will allow this easily from any machine. You'll need to have node and npm installed.

**Comment by LongLiveCHIEF** [comment]
@gitthismoney you can pull my PR, or wait for the merge: https://github.com/lloeki/matterfront/pull/19

**Comment by LongLiveCHIEF** [comment]
This has been merged. You can now follow the instructions on the README for [Build your own app](https://github.com/lloeki/matterfront/blob/master/README.md#building-your-own-app).

The default build now compiles an executable for every platform.
