### ISSUE TITLE
Set cursor to input box on channel change or focus

### ISSUE THREAD

**Issue by ohlookemus** [lloeki/matterfront#27]
Most chat applications on channel change or focus will set the cursor location to input area so that a user can begin typing immediately. Right now there is the minor inconvenience of swapping a channel, then clicking the input box to begin typing. Also could maybe allow tab index to be set to input box instead of other channels?

**Comment by lloeki** [comment]
Does it happen in a browser too? That may be a Mattermost, not Matterfront, issue.

**Comment by ohlookemus** [comment]
Happens in browser yea. Curious if there was a way to specify it to not do it specifically in the matterfront app. Similar to the recent webview.focus() PR. If it's not possible then it's not a big deal.

**Comment by ohlookemus** [comment]
Closing as 1.2 of MM addresses this.
