### ISSUE TITLE
Layout problems after upgrade to Mattermost 1.2.x

### ISSUE THREAD

**Issue by teetrinkers** [lloeki/matterfront#28]
When I upgraded our Mattermost server to 1.2.0-rc1, the layout in matterfront was messed up (see below). E.g., the entire page scrolls and the search options bubble wouldn't go away.

I was able to fix this by deleting the local data of the matterfront app in "/Users/theess/Library/Application Support/Matterfront", so this seems to be some kind of caching problem.

![f9cdce38-87ae-11e5-9821-f5863ea4db67](https://cloud.githubusercontent.com/assets/51070/11089477/52426fd6-886a-11e5-8256-69d5b95c6681.png)

**Comment by lloeki** [comment]
Did you try to reload with CMD+R?

**Comment by teetrinkers** [comment]
Yes, I did. Didn't help.

Btw I have also seen this behaviour in Chrome the first time I connected to the upgraded Mattermost server. Cmd-R did fix this in Chrome but not in Matterfront. Is the cache of the webview-container cleared on Cmd-R?

You can probably reproduce it using the following steps:
- Run Mattermost 1.1  
  `docker run --name mattermost-dev -d --publish 8065:80 mattermost/platform:1.1`
- Start and log in with Matterfront.
- Delete the docker container.
- Run Mattermost dev  
  `docker run --name mattermost-dev -d --publish 8065:80 mattermost/platform:dev`
- Start the Matterfront app used above.

**Comment by LongLiveCHIEF** [comment]
I was talking to @i3tt earlier yesterday afternoon, and there are some bugs in `1.2` around layout. This might get fixed regardless of any actions we take.

Even if we wind up taking no action to fix however, I think it will be good to definitively identify this behavior within Matterfront's ecosystem.

**Comment by it33** [comment]
Hi @H3Chief, the layout issue in v1.2 is the following: 
- When navigating to a page with new messages as well as message containing inline images added via markdown, the channel may move up and down while loading the inline images

There's a Known Issue that will be added to the release notes since we weren't able to solve it before everything was locked down. That's the known layout issue, this sounds more like caching to me. 

Happy to take any feedback on what Mattermost might to do work better here.

**Comment by lloeki** [comment]
This indeed looks like a cache issue:
- upgraded our server to 1.2.1, the app exhibited layout issues
- went to a browser, and layout issues came up
- refreshed the browser (possibly a couple of times) and layout issues went away
- tried to refresh the app but was hit by #31 
- tried to quit and restart the app, to no avail
- removed app data directory and restarted the app, issues vanished

**Comment by LongLiveCHIEF** [comment]
sorry guys, I was sick yesterday. I actually won't be able to look at this for probably another 30 hours.

**Comment by lloeki** [comment]
It seems https://github.com/mattermost/platform/pull/1454 will fix the "MM upgraded bug cache busted and doesn't reload assets" issue.

**Comment by Juburin** [comment]
For me the error no longer occurs after updating to Mattermost 1.3.0.

**Comment by lloeki** [comment]
The new _clear cache and reload_ feature helps force-clearing stale cache. That's the best we can do for now.
