### ISSUE TITLE
Review License Requirements

### ISSUE THREAD

**Issue by LongLiveCHIEF** [lloeki/matterfront#29]
We need to take a look at our license, and try to make a determination on whether or not Matterfront is a "derivative work", in which case, we'd need to adopt their license.

**Comment by lloeki** [comment]
I think we cross the line when we don't just embed   MM but inject code (e.g for badges). Either way I'm fine with switching to AGPL as it doesn't preclude internally distributed custom builds.

**Comment by LongLiveCHIEF** [comment]
Ultimately it's your repo, so it's your call. I leaned towards yes, since our product hinges on MM (it's not a swappable dependency, and the user is still interacting primarily with MM)... but I'm no expert here.

However, the "distributed" version of MM is MIT... so under that line of thought, the product we're actually engaging with is under the MIT license.  Even if it's truly a derivative work, then it's a derivative of the MIT version.

I think it's good we had the discussion, but let's just leave it for now unless something comes up.
