### ISSUE TITLE
Failure while trying to install

### ISSUE THREAD

**Issue by forelabs** [lloeki/matterfront#33]
Hi, I hope you can help me.
I installed npm and node (linux ubuntu 14.04) and tried to install via `npm install`
but it says:

```
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 1
npm ERR! not ok code 0
```

How can I fix this?

**Comment by forelabs** [comment]
Fixed it with using nodejs instead of node and link nodejs binary to node

**Comment by lloeki** [comment]
Possibly you'd want to [install nodejs from upstream](https://github.com/nodesource/distributions#debian-and-ubuntu-based-distributions).
