### ISSUE TITLE
No notification when minimized and in active chat.

### ISSUE THREAD

**Issue by stefnats** [lloeki/matterfront#34]
Situation:

I'm chatting with user foo and i'm minimizing matterfront, but i don't get notified when i'm in an active chat with foo, only when i'm chatting in another group / with another user.

Matterfront 1.0 on Windows 7 Pro.

**Comment by teetrinkers** [comment]
Are you talking about the desktop notification or the unread count badge in the task bar? There should be a desktop notification, but unfortunately there will not be an unread badge. This is probably related to mattermost/platform#975.

**Comment by stefnats** [comment]
Yes, exactly. I'm talking about the count badge.

**Comment by enahum** [comment]
I have solved this by adding a console.log in the mattermost code and then listening to the console event in matterfront, you could do something like that too. I admit is a shitty hack but it works for me :)

**Comment by teetrinkers** [comment]
@enahum: Awesome! Can you post a patch, so that we can have a look at it? Maybe it'll give us an idea for a cleaner solution.

**Comment by enahum** [comment]
What I did is pretty ugly but it works.
1. In mattermost utils.jsx in the notification on click event I added a console.log("notification")
2. in matterfront load-scr.js in the webview on console-message event I added this:
   
   if(event.message === "notification") {
       mainWindow.show();
    }

Thats all :)

**Comment by terghalin** [comment]
Notifications didn't work on Win8 and Win 8.1, no tray icon.

**Comment by LongLiveCHIEF** [comment]
We are working on some updates to support multiple teams and notifications.  Keep an eye out for release v1.3.0.

**Comment by LongLiveCHIEF** [comment]
Latest merges take care of this need in a sufficient manner, and will be rolled out officially in the 1.3 release. To get this capability now, build from master, and make sure to see the new instructions about adding teams in the README.md
