### ISSUE TITLE
No connection using self signed certificate

### ISSUE THREAD

**Issue by elpatron68** [lloeki/matterfront#35]
I tried to start matterfront against our nginx-proxied ssl site (https://mattermost.oursite.local), which is using a self-signed certificate, but I can´t connect. Using a direct (unsecured) connection against port 8065 works just fine. Is there anything I can do about it?

Thanks,
Markus

**Comment by daemongh** [comment]
Can you try to run the application with the `--ignore-certificate-errors` argument?

**Comment by elpatron68** [comment]
Hi @daemongh
--ignore-certificate-errors helps, the app starts successfully. Could it be made configurable before building?
Thanks, Markus

**Comment by LongLiveCHIEF** [comment]
@elpatron68 yes it can! It's a feature I'm adding in for the 1.2 release actually, along with proxy support.

you'll be able to add it to a config file, OR specify it as a build or run argument using the new matterfront-cli.  Check out the [_addCLI_](https://github.com/lloeki/matterfront/tree/addCLI) branch for a sneak peak.
