### ISSUE TITLE
App starts but closes immediately

### ISSUE THREAD

**Issue by lloeki** [lloeki/matterfront#37]
Seems like electron 0.34.3 and up (incl. 0.35.0) has an issue. Reverting to 0.34.2 solves it.

**Comment by teetrinkers** [comment]
master is on electron 0.35.4, so I think this can be closed.

**Comment by lloeki** [comment]
I'll check if I can repro it on master

**Comment by LongLiveCHIEF** [comment]
@lloeki where did you find the info on the electron issue? Can you link to it?

**Comment by lloeki** [comment]
I didn't find anything upstream, just got alerted by coworkers that there was such a regression, and pinpointed it to bumping Electron past 0.34.3. Maybe it's something in our env, so I wanted to repro locally with the latest Matterfront code and updated Electron.

**Comment by lloeki** [comment]
Seems fixed on master with 0.35.4, closing.
