### ISSUE TITLE
Icon should comply with Mattermost branding guidelines

### ISSUE THREAD

**Issue by lloeki** [lloeki/matterfront#5]

**Comment by LongLiveCHIEF** [comment]
Is this still an issue? I'm guessing the change you made to the icon a while back actually takes care of this, correct?

**Comment by lloeki** [comment]
I simply composed the Mattermost logo with a OS X icon blueprint canvas (including the subtle gradient to have it blend best on an OS X platform), which I had some doubts was allowed according to the guidelines. Yet, given how the brand new official iOS app icon is made (basically the same strategy) I suppose we're in fact doing OK, so let's close this.
