### ISSUE TITLE
Persistence (via tray icon?) on Windows

### ISSUE THREAD

**Issue by lloeki** [lloeki/matterfront#6]
Dunno what's more idiomatic these times around since W7 (since I'm not a Windows user), but tray area seems to be dropping out of favor, possibly preferring dock-ish pinned apps.

**Comment by lloeki** [comment]
Alternative: minimize, but the tray icon may be used for notification status. See #14.

**Comment by lloeki** [comment]
Notification status (a.k.a badge) has been handled by #16.

**Comment by LongLiveCHIEF** [comment]
Teams and mention badges also introduced in #67
