### ISSUE TITLE
White page after npm start

### ISSUE THREAD

**Issue by stefnats** [lloeki/matterfront#63]
Hi,

i just get a white page with the current git tree and with the current release (1.2.0).

After doing "npm install" and "npm start" it just shows a blank page - even if i put the config.json in the project root in which i define the team url. Am i doing something wrong or is this a bug?

**Comment by ninja-** [comment]
Afaik the behaviour of npm start has changed recently and it's no longer enough to start matterfront. I don't remember what's the correct command right now.

**Comment by stefnats** [comment]
Okay... Anybody knows this?
I'm using also npm run start which has the same effect.

**Comment by LongLiveCHIEF** [comment]
There _are_ new features being added with every version, and as such, the way you run matterfront _may_ ocassionally change.  You can view changes in the release comments, and the [README.md](https://github.com/lloeki/matterfront) has been updated to reflect the new run instructions.

**Comment by LongLiveCHIEF** [comment]
You could also try running the latest master branch from the repo where we do most of the work: https://github.com/StateFarmIns/matterfront

**Comment by stefnats** [comment]
I hate to reopen this, but i still don't get it. This is what i do:
1. `git clone https://github.com/StateFarmIns/matterfront.git`
2. `cd matterfront`
3. `npm install`
4. `npm link`
5. edit ~/.matterfront/state.json to look like the example in StateFarmIns/matterfront/README.md
6. edit ~/.matterfront/config.json to look like the example chrome args in README.md
7. `npm run start`

Environment is: Mac OS X 10.11, Node version 5.2.0
Latest commit is 01ba2df

Why am i still getting a blank page inside of matterfront?

This is the log from `npm install`: http://pastebin.com/h82PAb7R

Same happens with lloeki/matterfront (release and current master)

My goal is to create production apps to distribute in our office.

**Comment by lloeki** [comment]
Insert `npm run start-watch` or `npm run js` before step 7.

**Comment by stefnats** [comment]
Okay, running and building works now :-)
But:

When i build it and distribute it on other windows machines (win32-x64), it returns the same javascript error as i get on my dev machine when running without `~/.matterfront/config.json` and `~/.matterfront/state.json`
Is there a way to package those? This is the error:

```
Uncaught Exception:
TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at Object.chromeArgs.apply (/Users/stefuNz/Downloads/matterfront/dist/Matterfront-darwin-x64/Matterfront.app/Contents/Resources/app.asar/src/chrome-args.js:7:10)
    at Object.<anonymous> (/Users/stefuNz/Downloads/matterfront/dist/Matterfront-darwin-x64/Matterfront.app/Contents/Resources/app.asar/src/main.js:10:12)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Object.<anonymous> (/Users/stefuNz/Downloads/matterfront/dist/Matterfront-darwin-x64/Matterfront.app/Contents/Resources/atom.asar/browser/lib/init.js:130:10)
    at Object.<anonymous> (/Users/stefuNz/Downloads/matterfront/dist/Matterfront-darwin-x64/Matterfront.app/Contents/Resources/atom.asar/browser/lib/init.js:132:4)
    at Module._compile (module.js:434:26)
```

Do i have to put both on the windows machines? What would be the exact path?

**Comment by lloeki** [comment]
> Is there a way to package those?

This is the goal of #56, which will allow for `state.json` to be prefilled.

> Do i have to put both on the windows machines? What would be the exact path?

Once merged, you'll create `src/state.json` and `npm run build` will get it.

**Comment by stefnats** [comment]
Alright, will watch this issue... Thanks!
