### ISSUE TITLE
Matterfront broken after Mattermost v1.3.0 update

### ISSUE THREAD

**Issue by bjoernr-de** [lloeki/matterfront#65]
Hi,

after updating mattermost to v1.3.0 the Matterfront client was "broken". The new CSS is not being loaded ( as the old version is cached?).
Same problem appears in normal Browser (Chrome), but easy to handle: CMD + Shift + R (on Mac for hard reload without using Cache)

Is there an equivalent solution for Matterfront? Simple Reload doesn't solve the problem.

**Comment by Juburin** [comment]
Deleting ~/Library/Application\ Support/Matterfront did the trick for me.

**Comment by lloeki** [comment]
Possibly you can restrict to deleting the `Cache` subdir.

**Comment by bjoernr-de** [comment]
Ok, that seems to be an option.

For a more user-friendly way:
Is it possible to add a "Clear cache" tab to Matterfront menu?

**Comment by stefnats** [comment]
+1

**Comment by bjoernr-de** [comment]
Created PR #68

**Comment by bjoernr-de** [comment]
Reopen
@lloeki Sorry, #68 didn't really fix it. Please see #69
