### ISSUE TITLE
Alternative location for settings

### ISSUE THREAD

**Issue by faroit** [lloeki/matterfront#76]
Currently the location for the settings file `state.json` is fixed to the users home directory. To build custom branded version of matterfront, it would nice to provide a default `state.json` within the matterfront application directory. That way one could build pre-configured binaries with team urls already set.

I guess, the more obvious way to simplify the setup process would be to add a preference window to the matterfront application. But still, this proposal would be a nice addition to enable pre-configured clients.

**Comment by bjoernr-de** [comment]
+1

**Comment by lloeki** [comment]
This is what #56 aims to provide.

**Comment by faroit** [comment]
@lloeki excellent! And sorry, I didn't look into the PRs.
