### ISSUE TITLE
Empty screen on OS X 10.11

### ISSUE THREAD

**Issue by maokomioko** [lloeki/matterfront#79]
Running both compiled/source versions of 1.2.0 result in empty screen coming up without any content.
I've tried waiting for a few minutes, but nothing happens.

No errors in console whatsoever.

OS X 10.11, node 5.3.0, npm 3.3.12

**Comment by LongLiveCHIEF** [comment]
See PR #75. As soon as that merges, this issue will be fixed.

**Comment by GhostLyrics** [comment]
Does that mean #75 blocks this issue or does that mean #75 will also fix this issue? I'm asking because checking out the `fix_no_name` branch and building it hasn't solved this issue for me.
