### ISSUE TITLE
Ffailed to load resource: net::ERR_FILE_NOT_FOUND browser-build/bundle.js Failed to load 

### ISSUE THREAD

**Issue by vcazan** [lloeki/matterfront#87]
Getting a 404 on bundle.js not sure where I should get it from. 

Clean install latest commit using windows 10

**Comment by LongLiveCHIEF** [comment]
what method are you using to install?

**Comment by vcazan** [comment]
npm install
npm link
npm run start

**Comment by LongLiveCHIEF** [comment]
I think you found a missing/unclear step in our docs.  Can you try something for me?  

Run 

```
$ npm run js
....will output a bunch of compile steps
Success!
$ npm run start
```

**Comment by vcazan** [comment]
That fixed my issue perfectly!

**Comment by LongLiveCHIEF** [comment]
Thanks for pointing out the gap. :100:
