### ISSUE TITLE
Here's another app. Want to collaborate?

### ISSUE THREAD

**Issue by teetrinkers** [lloeki/matterfront#9]
Hi! Great to see your app! There's another Mattermost app based on Electron here https://github.com/teetrinkers/electron-mattermost, which is a fork of https://github.com/yuya-oc/electron-mattermost. It already has a build script and a simple configuration dialog.

If my team decides to switch to Mattermost (from Jabber and Slack), I will probably work on the client some more. Would you like to collaborate?

**Comment by lloeki** [comment]
@teetrinkers sorry for not answering, things got off quite quickly and I had some great chat on the Core Mattermost team, and was kinda waiting to see where this would lead before making any decisions.

**Comment by teetrinkers** [comment]
No worries! Your project has a cool name and uses english commit messages, so I'd rather contribute here.
